### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1500
}
### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "b833612eab8946618853baa3755c9b45",
  "accountNumber": "1000000000",
  "amount": 1500
}

### query transaction
GET http://localhost:8080/transaction/b3b840f7cc504027859e3bda731f5756